name: dart_lint_hooks
description: A small collection of pre commit hooks to format and lint dart code
version: 0.1.0
homepage: https://github.com/Skycoder42/dart_lint_hooks

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.7.0
  crypto: ^2.1.5
  yaml: ^2.2.1
  meta: ^1.2.3
  args: ^1.6.0
  get_it: ^5.0.1

dev_dependencies:
  lint: ^1.2.0
  test: ^1.15.3
  mockito: ^4.1.1
  cider: ^0.0.5
  test_coverage: ^0.4.3

executables:
  dart_lint_hooks: dart_lint_hooks
